# 2.4 Тренажер по модулю

## Step 1. Задача
В течение некоторого периода ежедневно измерялись температуры в 0 и 12 часов в одном и том же месте. Также известна средняя статистическая суточная температура за аналогичный период, полученная в результате наблюдений за погодой за длительный период времени в рассматриваемой местности. Необходимо вывести номера дней, в которые средняя температура за сутки (вычисляется как среднее значение температуры в 0 и 12 часов) была выше средней статистической.

**Входные данные:**

* строка, состоящая из вещественных чисел, разделенных пробелами (значения температур в 0 часов);
* строка, состоящая из вещественных чисел, разделенных пробелами (значения температур в 12 часов);
* среднесуточная температура (вещественное число).

**Выходные данные:**

* номера дней, в которых температура была выше средней (нумерация дней начинается с 0), каждый номер выводится на отдельной строке.

___

**Sample Input:**
```
3.4 0.7 2.0 0.4 2.5 2.6 1.7 0.2 4.0 2.5
6.4 8.3 6.8 6.7 7.4 6.4 8.9 4.7 5.3 7.6
4.5
```
___

**Sample Output:**
```
0
4
6
8
9
```

In [1]:
# s00 = input()
# s12 = input()
# t_mean = float(input())

s00 = '3.4 0.7 2.0 0.4 2.5 2.6 1.7 0.2 4.0 2.5'
s12 = '6.4 8.3 6.8 6.7 7.4 6.4 8.9 4.7 5.3 7.6'
t_mean = 4.5

s00_list = s00.split()
s12_list = s12.split()
list_len = len(s00_list)

t_mean_list = [(float(s00_list[i]) + float(s12_list[i])) / 2 for i in range(list_len)]

for i in range(list_len):
    if float(t_mean_list[i]) > t_mean:
        print(i)

0
4
6
8
9

In [2]:
# Alternative

s00 = '3.4 0.7 2.0 0.4 2.5 2.6 1.7 0.2 4.0 2.5'
s12 = '6.4 8.3 6.8 6.7 7.4 6.4 8.9 4.7 5.3 7.6'
t_mean = 4.5

t00 = list(map(float, s00.split()))
t12 = list(map(float, s12.split()))

print(*[i for i in range(len(t00)) if (t00[i] + t12[i]) / 2 > t_mean], sep="\n")

0
4
6
8
9

## Step 2. Задача
Даны **n** населенных пунктов, каждый из которых в некоторой относительной системе координат имеет две координаты $x$ и $y$. В пункте с номером (индексом) **k** установлена радиостанция с радиусом действия  **r** км. Определить, сколько населенных пунктов попадает в радиус ее действия  (включая населенный пункт **k**).

**Входные данные:**

* строка, в которой через пробел перечислены координаты населенных пунктов по оси OX;
* строка, в которой через пробел перечислены координаты населенных пунктов по оси OY;
* номер населенного пункта **k** ( целое число в интервале от 0 до n-1);
* радиус действия радиостанции **r**.

**Выходные данные:**

* количество населенных пунктов, попадающих в радиус действия радиостанции.

___

**Sample Input 1:**
```
27 53 44 88 35 86 92 20 10 73 81
97 22 57 58 37 55 34 29 80 55 71
7
68
```
**Sample Output 1:**
```
6
```
___

**Sample Input 2:**
```
23 56 62 12 30 71 88 17 49 34 47 99 18 75 37
54 71 26 59 97 45 42 63 42 87 65 68 44 59 43
1
53
```
**Sample Output 2:**
```
15
```

In [3]:
# x_line = input().split()
# y_line = input().split()
# k = int(input())
# r = float(input())

x_line = '27 53 44 88 35 86 92 20 10 73 81'.split()
y_line = '97 22 57 58 37 55 34 29 80 55 71'.split()
k = 7
r = 68.

X = [float(x) for x in x_line]
Y = [float(x) for x in y_line]
n = len(X)

xk, yk = X[k], Y[k]

distances = [((X[i]-xk)**2 + (Y[i]-yk)**2)**0.5 for i in range(n)]

count = 0
for d in distances:
    if d <= r:
        count += 1
        
print(count)

6

In [4]:
# Alternative

x_line = '27 53 44 88 35 86 92 20 10 73 81'.split()
y_line = '97 22 57 58 37 55 34 29 80 55 71'.split()
k = 7
r = 68.

cities = list(zip(
    (int(x) for x in x_line), 
    (int(y) for y in y_line)
))

c_x, c_y = cities[k]

print(sum(1 for x, y in cities if (c_x - x) ** 2 + (c_y - y) ** 2 <= r ** 2))

6

## Step 3. Задача
Известны величины потребленной электроэнергии в некотором помещении  за каждый месяц года. Месячная норма потребления электроэнергии **n** кВт·ч , стоимость 1 кВт·ч в пределах нормы  **a** руб, и стоимость за каждый 1 кВт·ч потребления электроэнергии сверх нормы  **b** руб.  Вычислите суммарное потребление и стоимость электроэнергии за год.

**Входные данные:**

* строка, в которой через пробел перечислены значения потребленной энергии за каждый месяц (целые числа);
* месячная норма потребления **n** кВт·ч (целое число);
* стоимость  1 кВт·ч в пределах нормы  **a** руб (вещественное число);
* стоимость  1 кВт·ч сверх нормы  **b** руб (вещественное число).

**Выходные данные:**

* суммарное потребление электроэнергии за год;
* стоимость потребленной электроэнергии за год.

Для вывода используйте следующий формат:
```
"Сумма: %6d кВт ч, стоимость %7.2f руб"
```
___

**Sample Input:**
```
150 132 110 186 103 229 179 224 230 113 224 202
148
3.67
4.83
```
**Sample Output:**
```
Сумма:   2082 кВт ч, стоимость 8151.34 руб
```

In [5]:
# E = [int(e) for e in input().split()] # energy
# n = int(input())
# a = float(input())
# b = float(input())

# Energy by months
E = [int(e) for e in '150 132 110 186 103 229 179 224 230 113 224 202'.split()]
n = 148
a = 3.67
b = 4.83

# cost
#  
C = [ e*a * (e <= n) +           # before limit n
     (n*a + (e-n)*b) * (e > n)   # after limit n
     for e in E]        

print("Сумма: %6d кВт ч, стоимость %7.2f руб" % (sum(E), sum(C)))

Сумма:   2082 кВт ч, стоимость 8151.34 руб

## Step 4. Задача
Банки предлагают населению кредиты с двумя способами расчета ежемесячных платежей: аннуитетный  (когда человек ежемесячно платит одинаковую сумму во всем периоде кредитования) и дифференцированный (в этом случае ежемесячный платеж по погашению кредита постепенно уменьшается к концу периода кредитования).

Сумма кредита составляет **s** рублей, срок кредита n месяцев, процент - **k**%.

Для расчета платежа в месяц **t** при дифференцированной выплате  используется формула:

$$
\begin{equation*}
    p_d(t) = \frac{s}{n} + (s-(t-1)\cdot \frac{s}{n})\cdot \frac{k}{12\cdot 100}
\end{equation*}
$$

Для расчета ежемесячного платежа при аннуитетной выплате используется формула:

$$
\begin{equation*}
    k_a = \frac{k}{12\cdot 100} \\
    p_a(t) = \frac{k_a\cdot(1+k_a)^n}{(1+k_a)^n-1}
\end{equation*}
$$

Вычислить ежемесячные платежи для каждого месяца, а также доход банка при каждом способе (разница между суммарной выплатой и суммой кредита).

**Входные данные:**

* сумма кредита **s** руб (целое число);
* срок кредита **n** месяцев (целое число);
* процент **k** (целое число).

**Выходные данные:**

* **n** строк, на каждой из которой выведены платежи двумя способами выплаты, используя формат:
```
           "%2d месяц - (диф.) %8.2f руб - (анн.) %8.2f руб".
```
* доход банка при каждом способе выплаты, для вывода использовать формат:
```
           "Доход банка - (диф.) %6.2f руб - (анн.) %6.2f руб".
```
___

**Sample Input:**
```
1000000
12
15
```
___

**Sample Output:**
```
 1 месяц - (диф.) 95833.33 руб - (анн.) 90258.31 руб
 2 месяц - (диф.) 94791.67 руб - (анн.) 90258.31 руб
 3 месяц - (диф.) 93750.00 руб - (анн.) 90258.31 руб
 4 месяц - (диф.) 92708.33 руб - (анн.) 90258.31 руб
 5 месяц - (диф.) 91666.67 руб - (анн.) 90258.31 руб
 6 месяц - (диф.) 90625.00 руб - (анн.) 90258.31 руб
 7 месяц - (диф.) 89583.33 руб - (анн.) 90258.31 руб
 8 месяц - (диф.) 88541.67 руб - (анн.) 90258.31 руб
 9 месяц - (диф.) 87500.00 руб - (анн.) 90258.31 руб
10 месяц - (диф.) 86458.33 руб - (анн.) 90258.31 руб
11 месяц - (диф.) 85416.67 руб - (анн.) 90258.31 руб
12 месяц - (диф.) 84375.00 руб - (анн.) 90258.31 руб
Доход банка - (диф.) 81250.00 руб - (анн.) 83099.75 руб
```

In [6]:
def differentiated_payment(t, s, n, k):
    p = s/n + (s - (t-1) * s / n) * k / (12 * 100)
    return p

def annuity_payment(t, s, n, k):
    ka = k / (12 * 100)
    p = ka * (1+ka)**n / ((1+ka)**n - 1)
    p *= s
    return p
    
# s = int(input()) 
# n = int(input()) # months
# k = int(input()) # %

s = 1000000
n = 12
k = 15

month = [t for t in range(1, n+1)]
pd = [differentiated_payment(t, s, n, k) for t in range(1, n+1)]
pa = [annuity_payment(t, s, n, k) for t in range(1, n+1)]

for i in range(len(month)):
    print("%2d месяц - (диф.) %8.2f руб - (анн.) %8.2f руб" % (month[i], pd[i], pa[i]))

print("Доход банка - (диф.) %6.2f руб - (анн.) %6.2f руб" % (sum(pd) - s, sum(pa) - s))

 1 месяц - (диф.) 95833.33 руб - (анн.) 90258.31 руб
 2 месяц - (диф.) 94791.67 руб - (анн.) 90258.31 руб
 3 месяц - (диф.) 93750.00 руб - (анн.) 90258.31 руб
 4 месяц - (диф.) 92708.33 руб - (анн.) 90258.31 руб
 5 месяц - (диф.) 91666.67 руб - (анн.) 90258.31 руб
 6 месяц - (диф.) 90625.00 руб - (анн.) 90258.31 руб
 7 месяц - (диф.) 89583.33 руб - (анн.) 90258.31 руб
 8 месяц - (диф.) 88541.67 руб - (анн.) 90258.31 руб
 9 месяц - (диф.) 87500.00 руб - (анн.) 90258.31 руб
10 месяц - (диф.) 86458.33 руб - (анн.) 90258.31 руб
11 месяц - (диф.) 85416.67 руб - (анн.) 90258.31 руб
12 месяц - (диф.) 84375.00 руб - (анн.) 90258.31 руб
Доход банка - (диф.) 81250.00 руб - (анн.) 83099.75 руб